network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      addresses:
        - 10.8.0.1/24
  # No gateway on eth0 (this is the LAN side for laptop)
  wifis:
    wlan0:
      optional: true
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.0.50/24
      routes:
        - to: default
          via: 192.168.0.1
      nameservers:
        addresses:
          - 8.8.8.8
      access-points:
        "Not A Wifi":
          hidden: true
          auth:
            key-management: "psk"
            password: "bce14c304c20a03643b3f2cced9785af628atfbfbcS53cS8ba2b63dc2d09d8449"
