[Interface]
# Key for No-Pulse-HUB
PrivateKey = [PRIVATE_KEY_HERE]
Address = 10.2.0.2/32
#DNS = 10.2.0.1
# Kill Switch - Block traffic if VPN drops
PostUp = iptables -I FORWARD -o wlan0 -j REJECT
PreDown = iptables -D FORWARD -o wlan0 -j REJECT

[Peer]
# RO-FREE#5
PublicKey = jDAyArm/Gg+ONoEfAawsibdNRTTGZcfAvgan+bGD0G8=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 138.199.53.237:51820
PersistentKeepalive = 25
